export const REQ_POST_LOGIN_FORM_START = 'REQ_POST_LOGIN_FORM_START'
export const REQ_POST_LOGIN_FORM_SUCCESS = 'REQ_POST_LOGIN_FORM_SUCCESS'
export const REQ_POST_LOGIN_FORM_FAIL = 'REQ_POST_LOGIN_FORM_FAIL'

export const REQ_POST_LOGOUT_FORM_START = 'REQ_POST_LOGOUT_FORM_START'
export const REQ_POST_LOGOUT_FORM_SUCCESS = 'REQ_POST_LOGOUT_FORM_SUCCESS'
export const REQ_POST_LOGOUT_FORM_FAIL = 'REQ_POST_LOGOUT_FORM_FAIL'
